server:
  port: 9202

spring:
  application:
    name: socket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE_HOST:localhost}:3306/server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1234}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  websocket:
    server:
      max-text-message-size: 8388608
      max-binary-message-size: 8388608

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.example.socket.domain
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    root: INFO
    org.example.socket: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"